version = 1

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  import_root = "github.com/GMRiley/ecom/ecom-ui"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/GMRiley/ecom/ecom-api"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
